CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE mal_series (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mal_id INTEGER NOT NULL UNIQUE,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    alternative_titles JSONB,
    main_picture TEXT,
    start_date DATE,
    end_date DATE,
    synopsis TEXT,
    mean FLOAT,
    rank INTEGER,
    popularity INTEGER,
    num_list_users INTEGER,
    num_scoring_users INTEGER,
    nsfw TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    media_type TEXT,
    status TEXT,
    genres JSONB,
    my_list_status JSONB,
    num_episodes INTEGER,
    num_volumes INTEGER,
    num_chapters INTEGER,
    start_season JSONB,
    broadcast JSONB,
    source TEXT,
    average_episode_duration INTEGER,
    rating TEXT,
    pictures JSONB,
    background TEXT,
    related_anime JSONB,
    related_manga JSONB,
    recommendations JSONB,
    studios JSONB,
    statistics JSONB,
    authors JSONB,
    serialization JSONB,
    inserted_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_mal_series_mal_id ON mal_series(mal_id);
CREATE INDEX idx_mal_series_title ON mal_series(title); 