# -*- coding: utf-8 -*-
"""Copy of pyngrok - Colab HTTP Example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5T4nSDJdBknkepXvl_uzjxMZ1ZDeQCe
"""
import getpass
import os
import threading
from flask import Flask
from pyngrok import ngrok, conf

#TODO: add auth token to env variablew
print("Enter your authtoken, which can be copied from https://dashboard.ngrok.com/get-started/your-authtoken")
conf.get_default().auth_token = getpass.getpass()

app = Flask(__name__)
port = "5000"

# Open a ngrok tunnel to the HTTP server
public_url = ngrok.connect(port).public_url
print(f" * ngrok tunnel \"{public_url}\" -> \"http://127.0.0.1:{port}\"")

# Update any base URLs to use the public ngrok URL
app.config["BASE_URL"] = public_url

# ... Update inbound traffic via APIs to use the public-facing ngrok URL


# Define Flask routes
@app.route("/")
def index():
    return "Hello from Colab!"

# Define your function
def my_function(x, y):
    return x + y

# Create an endpoint to handle the POST request
@app.route('/compute', methods=['POST'])
def compute():
    data = request.json  # get the JSON data from the request body
    x = data.get('x')
    y = data.get('y')

    result = my_function(x, y)

    return jsonify({'result': result})

import numpy as np
from PIL import Image
import logging

# Configure logging (you can adjust the level and format as needed)
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


def maketile(image_np: np.ndarray) -> list[np.ndarray]:
    """
    Splits the input image (as a NumPy array) into vertical tiles with a fixed width equal to
    the original image width, a height three times the width, and a 20% overlap.

    Args:
        image_np: The input image as a NumPy array.

    Returns:
        A list of image tiles as NumPy arrays.
    """
    logging.info("Starting maketile function")
    img_height, img_width, _ = image_np.shape
    logging.info(f"Image dimensions: height={img_height}, width={img_width}")

    tile_height = 3 * img_width
    overlap_height = int(0.20 * tile_height)
    logging.info(f"Calculated tile height: {tile_height}, overlap height: {overlap_height}")

    tiles = []
    start_y = 0
    tile_count = 0

    while start_y < img_height:
        end_y = min(start_y + tile_height, img_height)
        tile_np = image_np[start_y:end_y, :, :]
        tiles.append(tile_np)

        logging.info(f"Created tile {tile_count} from y={start_y} to y={end_y}")
        tile_count += 1

        start_y += tile_height - overlap_height
        # Ensure the last tile covers the remaining part if it's smaller than tile_height
        if start_y >= img_height - overlap_height and end_y < img_height:
             start_y = img_height - tile_height


    logging.info(f"Finished maketile function, created {len(tiles)} tiles.")
    return tiles

# Rerun if you attatch a GPU
from easyocr import Reader

reader = Reader(['ko'])

import numpy as np
from PIL import Image # Keep PIL for potential conversions if needed by runOCR, but aim for numpy in/out

def runOCR(tile_np: np.ndarray) -> list[str]:
    """
    Performs OCR on a given image tile (as a NumPy array) using the EasyOCR reader and returns
    a list of extracted Korean words.

    Args:
        tile_np: The image tile as a NumPy array.

    Returns:
        A list of extracted Korean words (strings).
    """
    # Perform OCR on the tile (EasyOCR's readtext can accept NumPy arrays)
    results = reader.readtext(tile_np, detail=0) # detail=0 returns only the text

    # Filter for Korean words (EasyOCR handles language detection)
    # In this case, since the reader is initialized for Korean, we expect Korean results.
    # We can directly return the results.
    return results

from flask import request, jsonify
from PIL import Image
import io
import numpy as np

def process_image():
    if "image" not in request.files:
        return jsonify({"error": "No image file found"}), 400

    file = request.files["image"]
    # Open the image using PIL and convert to NumPy array
    image = Image.open(io.BytesIO(file.read())).convert("RGB") # Ensure RGB for consistent processing
    image_np = np.array(image)

    tiles_np = maketile(image_np)
    all_words = []
    for tile_np in tiles_np:
        words = runOCR(tile_np)
        all_words.extend(words)

    return jsonify({"words": all_words})

@app.route("/process_image", methods=["POST"])
def process_image_route():
    return process_image()

# Start the Flask server in a new thread
threading.Thread(target=app.run, kwargs={"use_reloader": False}).start()

import requests
from PIL import Image
import io


image_path = "/content/row-1-column-1.jpg"

# prompt: test thefunctions (not endpoint) with the image above

# Test maketile function
tiles = []
try:
    test_image = Image.open(image_path)
    # Convert PIL Image to NumPy array before passing to maketile
    test_image_np = np.array(test_image.convert("RGB")) # Ensure RGB for consistent processing

    tiles_np = maketile(test_image_np)
    print(f"maketile produced {len(tiles_np)} tiles.")
    # You can optionally save the tiles to see the output
    # for i, tile in enumerate(tiles_np):
    #     # Convert NumPy array back to PIL Image for saving if needed
    #     Image.fromarray(tile).save(f"tile_{i}.jpg")
    # print("Tiles saved for inspection.")
except Exception as e:
    print(f"Error testing maketile: {e}")

# Test runOCR function with the first tile (which is now a NumPy array)
if tiles_np: # Check if tiles_np is not empty
    all_words = []
    try:
      words_0 = runOCR(tiles_np[0])
      all_words.append(words_0)
      words_1 = runOCR(tiles_np[1])
      all_words.append(words_1)
      words_2 = runOCR(tiles_np[2])
      all_words.append(words_2)
      print(f"runOCR on tile found: {all_words}")
    except Exception as e:
        print(f"Error testing runOCR: {e}")
else:
    print("Could not test runOCR because maketile did not produce tiles.")

# prompt: write a test to test the "hello from colab" endpoint

# Test the "/" endpoint
try:
    response = requests.get(public_url)
    if response.status_code == 200:
        print(f"Test of / endpoint successful. Response: {response.text}")
    else:
        print(f"Test of / endpoint failed. Status code: {response.status_code}")
except requests.exceptions.RequestException as e:
    print(f"Error testing / endpoint: {e}")

# prompt: now test the image one

# Keep the server running for potential external requests if needed
# You might want to add a loop or mechanism to keep the notebook alive
# or stop it gracefully if necessary.
# In a Colab notebook, the cell execution finishing will stop the server thread.
# If you need it to run longer, you'd typically move this to a more persistent environment.

# Test the "/process_image" endpoint
try:
    # Assuming 'image_path' and 'public_url' are defined in previous cells
    with open(image_path, 'rb') as f:
        files = {'image': f}
        response = requests.post(f"{public_url}/process_image", files=files)

    if response.status_code == 200:
        print(f"Test of /process_image endpoint successful. Response: {response.json()}")
    else:
        print(f"Test of /process_image endpoint failed. Status code: {response.status_code}, Response: {response.text}")
except requests.exceptions.RequestException as e:
    print(f"Error testing /process_image endpoint: {e}")

# Restart the Flask server in a new thread
# Check if the thread is alive before starting to avoid multiple server instances
if not any('__name__' == 'FlaskServerThread' for thread in threading.enumerate()):
    flask_thread = threading.Thread(target=app.run, kwargs={"use_reloader": False}, name='FlaskServerThread')
    flask_thread.start()
    print("Flask server thread started.")
else:
    print("Flask server thread is already running.")

!curl -X POST "http://127.0.0.1:5000/compute" -H "Content-Type: application/json" -d '{"x": 3, "y": 4}'

import cv2
import numpy as np
import io
from flask import request, jsonify

def process_image_cv2():
    if "image" not in request.files:
        return jsonify({"error": "No image file found"}), 400

    file = request.files["image"]
    # Read the image file into a byte array
    image_bytes = file.read()
    # Convert byte array to numpy array
    image_np = np.frombuffer(image_bytes, np.uint8)
    # Decode the image using OpenCV
    image_cv2 = cv2.imdecode(image_np, cv2.IMREAD_COLOR) # Use IMREAD_COLOR for RGB

    if image_cv2 is None:
         return jsonify({"error": "Could not decode image"}), 400

    # Convert BGR (OpenCV default) to RGB if your maketile function expects RGB
    image_rgb = cv2.cvtColor(image_cv2, cv2.COLOR_BGR2RGB)


    tiles_np = maketile(image_rgb) # Use the maketile function that expects a NumPy array
    all_words = []
    for tile_np in tiles_np:
        words = runOCR(tile_np) # Assuming runOCR can handle NumPy arrays
        all_words.extend(words)

    return jsonify({"words": all_words})

# You would then update your route to use this new function:
# @app.route("/process_image", methods=["POST"])
# def process_image_route():
#     return process_image_cv2()